version: '3'
services:
  flash-memorizer-db:
    container_name: book-store-db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=BookStore
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - book-store-data:/var/lib/mysql

volumes:
  book-store-data: